### ISSUE TITLE
Reference table to docs

### ISSUE THREAD

**Issue by pylang** [erikrose/more-itertools#214]
It is feasible to get a reference table like the following in the docs:

![2018-06-11 16_39_32-aiostream aiostream documentation](https://user-images.githubusercontent.com/10778668/41255978-415a105c-6d96-11e8-9e18-f39bcbc4b283.png)

The tools are presented in a table by category.  Clicking each tool takes you to the api docs.   

We've had a similar discussion in the past (#130) that led to categories in the docs (https://github.com/erikrose/more-itertools/pull/133, thanks @bbayles).   I think a quick table on the landing page would improve:

- finding a specific tool: now I click on `API Reference`, then <kbd>Ctrl</kbd> + <kbd>F</kbd> and search by name to find details on a certain tool
- seeing all tools pertaining to a category at a glance: now we click on a category and scroll through the tools until we hit the next category.

FYI: the example above is from [`aiostream`](https://aiostream.readthedocs.io/en/latest/) (think `asyncio` + `itertools`).   I've also seen a table-like listing of tools in @MSeifert04's [`iteration_utilities`](https://iteration-utilities.readthedocs.io/en/latest/). Perhaps he can comment on ease of maintainability.

**Comment by MSeifert04** [comment]
For the main overview tables in `iteration_utilities` I use a [helper](https://github.com/MSeifert04/iteration_utilities/blob/master/helper/create_functions_table.py) based on AstroPys Table that creates that RST table. One just has to remember updating it.

If you just want a `aiostream`-like table that should be relatively easy, because the order of the cells doesn't change it's not too complicated to maintain it manually. If you need help with the initial creation I can probably help there. Automation could also be possible but in that case you probably need some marker (private property, doc parsing or something like that) to group them by.

**Comment by bbayles** [comment]
Thanks for the note. I'm positive on the idea; if someone makes a PR for it I will trigger a ReadTheDocs build, and if it looks good will merge it.
