### ISSUE TITLE
locate_seq, replace, and replace_seq

### ISSUE THREAD

**Issue by bbayles** [erikrose/more-itertools#220]
I may get to vetting these properly myself, but in case anybody watching is interested in taking that up: I pushed [a branch](https://github.com/erikrose/more-itertools/compare/replace?expand=1) with three new functions:
* `locate_seq`: Like `locate`, but for a sequence of items.
* `replace`: Like `str.replace`, but replacing single items in iterables.
* `replace_seq`: Like `replace`, but for sequences of items.

If these were proposed by someone else I think I would merge them, since they extend built-in functionality to iterables and proved to be tricky to get right.

However, these are questions I'd like to answer:
* Is there any actual need? How many StackOverflow questions are there around each? comp.lang.python threads?
* Is `replace` needed if `replace_seq` is there?
* What edge cases should be added in tests?
* Are there better / faster implementations? Especially for `replace_seq`?

**Comment by pylang** [comment]
Cool.  My knee-jerk reactions are:

1. `locate_seq` -1 (name)
1. `replace` +1 (utility)
1. `replace_seq` +0 (uniqueness)

Details

1. By the name alone, I assumed this was a `locate` tool for Python sequences, collections that can be sliced.  `seq` doesn't have to be a sequence though.  An iterator can be used too, so the name throws me a bit.  You mean a "sequence" of adjacent items, or what I'd consider a window, but I'm not sure what is a better name.  Last bit, it's not quite like `locate` since it does not accept a predicate, so I think `locate_...` might be confusing.
1. I've been itching for a tool like this for ages.  This is great.
1.  If my goal was to "replace" items in an iterable, I'd probably reach for `replace` and see what I could with it first before seeking any other tool.  I'd prefer to see this feature rolled into a single `replace` function, but  I know that would a beast of a function to implement. 

Those are quick thoughts.  I'll have to take more time to look at them closely.  Thanks for the contrib!

**Comment by bbayles** [comment]
I thought of a way to merge `locate` and `locate_seq`, which I think is probably the way to go with that. It doesn't map exactly on to `rlocate`, but can probably be made to work. I've pushed that branch.

What about the name `splice` instead of `replace_seq`?

**Comment by pylang** [comment]
`locate` (merger) +1
- [Python: Find a substring in a string and returning the index of the substring](https://stackoverflow.com/questions/21842885/python-find-a-substring-in-a-string-and-returning-the-index-of-the-substring)
- [Find indexes of sequence in list in python](https://stackoverflow.com/questions/10459493/find-indexes-of-sequence-in-list-in-python)
- [Best way to determine if a sequence is in another sequence in Python](https://stackoverflow.com/questions/425604/best-way-to-determine-if-a-sequence-is-in-another-sequence-in-python)



`replace` (idea) +1
- [finding and replacing elements in a list (python)](https://stackoverflow.com/questions/2582138/finding-and-replacing-elements-in-a-list-python)
- []()
- []()


`splice` (name): +0 I like the name, but i think it would be analogous to `interleave`
- [Replace sequence in list with a value in Python](https://stackoverflow.com/questions/30017405/replace-sequence-in-list-with-a-value-in-python); what happens if the old and new sequences aren't equal length?
- [Search and replace multiple specific sequences of elements in Python list/array](https://stackoverflow.com/questions/38969984/search-and-replace-multiple-specific-sequences-of-elements-in-python-list-array)
- [How to replace all instances of a sub-sequence in a list in Python?](https://stackoverflow.com/questions/9683745/how-to-replace-all-instances-of-a-sub-sequence-in-a-list-in-python)

**Comment by bbayles** [comment]
Good point! I wound up not using it in PR #221.

**Comment by erikrose** [comment]
Heh, yes, I noticed that as I churned through later PR mails. :-) Good work, as always!
