### ISSUE TITLE
[Feature] Add left padding to windowed

### ISSUE THREAD

**Issue by Vimos** [erikrose/more-itertools#265]
How about adding a feature to support a similar function like below?

```
In [11]: from itertools import chain
In [12]: padding = iter([None] * 2)
In [13]: list(windowed(chain(padding, range(10)), 3))
Out[13]: 
[(None, None, 0),
 (None, 0, 1),
 (0, 1, 2),
 (1, 2, 3),
 (2, 3, 4),
 (3, 4, 5),
 (4, 5, 6),
 (5, 6, 7),
 (6, 7, 8),
 (7, 8, 9)]

```

**Comment by bbayles** [comment]
Thanks for the note.

Could you describe your application? I looked at this when I was doing the implementation of `windowed`, but decided against it because it complicates the code.

I would accept a PR that adds a note to the docstring that shows how you use `chain` to do it; that's looks exactly like what I would do.

**Comment by Vimos** [comment]
I came into this because I was dealing with conversation history windowing, I need to pad left to initialize the windowing to show that it has no history.

I think using `chain` is more pythonic.

One more thing, sometimes users may prefer padding a default object rather than `None` .

If you think it's interesting, feel free to add to docstring.
