### ISSUE TITLE
list(bucket()) hangs with 100% CPU

### ISSUE THREAD

**Issue by alexchandel** [erikrose/more-itertools#370]
From the docs:

```py
b = bucket(['a1', 'b1', 'c1', 'a2', 'b2', 'c2', 'b3'], lambda x: x[0])
```

The following uses 100% CPU and never returns:
```py
list(b)
```

Additionally, `dict(b)` fails with `dictionary update sequence element #0 has length 0; 2 is required`, leaving no way to inspect the opaque result without prior knowledge of all keys.

This occurs in all versions of more-itertools.

**Comment by MSeifert04** [comment]
`bucket` itself is an infinite iterable. That's why it hangs.

However maybe `bucket` is only iterable by accident (it implements `__getitem__` so it's iterable) - I'm not sure.

But yeah, `bucket` (as it currently is) isn't meant to be iterated over without knowledge of the keys.

**Comment by bbayles** [comment]
Correct - this was discussed [at the time of implementation](https://github.com/erikrose/more-itertools/pull/66#issuecomment-259875648).

**Comment by bbayles** [comment]
Because `__getitem__` is implemented, when calling `list()` or `dict()` on `bucket(something)` causes Python to look up `0`, `1,`, `2`... on to infinity.

https://github.com/erikrose/more-itertools/pull/371 prevents this by explicitly defining `__iter__`. Now calling `list()` on `bucket(something)` will extract the keys from the iterable and return them.
