### ISSUE TITLE
more.chunked API inconsistent with recipes

### ISSUE THREAD

**Issue by jaraco** [erikrose/more-itertools#38]
Recipes.grouper has this signature:

```
def grouper(n, iterable, fillvalue=None):
```

But more.chunked has this signature:

```
def chunked(iterable, n):
```

Because these two functions serve almost exactly the same purpose, only with chunked not providing any fill value, it would be nice if it also had a congruent interface.

I know it's a lot to ask for an API to change so dramatically, but I think it would be worth the backward-incompatible change to make these congruent.

I make this post for your consideration and feedback. I won't be offended if the idea is rejected.

**Comment by bbayles** [comment]
I agree aesthetically, and if `consume`, `nth`, and `ncycles` were all the same, I'd be all for the change - but since those are the opposite I think it's probably not worth the switch for this one.

If we figure out time travel, this will be on my list! Not very high up, but definitely on it. ![lkh](https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/TARDIS-trans.png/30px-TARDIS-trans.png)
